"""empty message

Revision ID: 933f9212077f
Revises: 67fbd274d3e0
Create Date: 2018-11-16 16:36:43.027977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933f9212077f'
down_revision = '67fbd274d3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
